[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--include=dev"
  VITE_API_URL = "https://huntrix.onrender.com"

# Proxy API calls in development & build to Render
[[redirects]]
  from = "/api/*"
  to = "https://huntrix.onrender.com/:splat"
  status = 200
  force = true